### PR TITLE
#2 fix android issue and also refix ios

### LINKED ISSUE #2: Fix splash screen for android

### PR DESCRIPTION
**Pull request by alielzei**
This should fix #2

### CODE REVIEW

**Comment by shouryan01** [comment]
https://user-images.githubusercontent.com/32345320/236593272-27023076-28de-4c56-8b11-e29ca05ef859.mov

Looks better now. Still getting a flutter circle icon before the splash screen though

**Comment by alielzei** [comment]
Oh I dont know why I didnt get that. It looks funny, gotta fix that, should be done by deleting a line somewhere in the android directory. android/res/app/...

Which brings us to the point that we need to make sure that no one changes with the ios or android directories, because that would cause these kind of fixes to be broken. So the reviewer has to take a look at which files were changed and keep an extra eye on these directories. 

Sometime I tend to delete the ios directory and create it again when I break it in Xcode cause I dont know much in Xcode, which would cause things to go away.

Also it looks like theres no ios file change in this PR which means I didnt refix for ios, so I will handle that too.

**Comment by alielzei** [comment]
I think the flutter logo is related to the app logo. It should change with that. Let us try changing the app icon and see what happens?

**Comment by shouryan01** [comment]
> I think the flutter logo is related to the app logo. It should change with that. Let us try changing the app icon and see what happens?

yeah honestly it's not a big deal. if you know where that file is, just replace that with this logo and then it'll be okay

HD2 logo

**Comment by shouryan01** [comment]
still getting that error. What emulator are you using? I have pixel 3a. I'm guessing that's a pretty old device to be testing on tbh

**Comment by alielzei** [comment]
No your device is newer than the device I used to test, I used your same Android version and device and I got the same thing. Must be the app icon.

**Comment by shouryan01** [comment]
were you able to replace the app icon?

**Pull request merged**
